// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20210120222657_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Rating");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Author = "John Snow",
                            City = "Seattle, WA",
                            Country = "USA",
                            Rating = 5,
                            ReviewText = "Great city"
                        },
                        new
                        {
                            ReviewId = 2,
                            Author = "Pamela Anderson",
                            City = "Los Angeles, CA",
                            Country = "USA",
                            Rating = 4,
                            ReviewText = "Dirty city"
                        },
                        new
                        {
                            ReviewId = 3,
                            Author = "John Sun",
                            City = "Tucson, Az",
                            Country = "USA",
                            Rating = 3,
                            ReviewText = "Hot city"
                        },
                        new
                        {
                            ReviewId = 4,
                            Author = "John Snow",
                            City = "Tomsk",
                            Country = "Russia",
                            Rating = 2,
                            ReviewText = "Cold city"
                        },
                        new
                        {
                            ReviewId = 5,
                            Author = "A. Lukashenko",
                            City = "Mogilev",
                            Country = "Belarus",
                            Rating = 1,
                            ReviewText = "Terrible city"
                        },
                        new
                        {
                            ReviewId = 6,
                            Author = "Serge Bash",
                            City = "Minsk",
                            Country = "Belarus",
                            Rating = 1,
                            ReviewText = "OK city"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
