// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    partial class TravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("Rating");

                    b.Property<string>("Text");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Author = "John Snow",
                            City = "Seattle, WA",
                            Country = "USA",
                            Rating = 5,
                            Text = "Great city"
                        },
                        new
                        {
                            ReviewId = 2,
                            Author = "Pamela Anderson",
                            City = "Los Angeles, CA",
                            Country = "USA",
                            Rating = 4,
                            Text = "Dirty city"
                        },
                        new
                        {
                            ReviewId = 3,
                            Author = "John Sun",
                            City = "Tucson, Az",
                            Country = "USA",
                            Rating = 3,
                            Text = "Hot city"
                        },
                        new
                        {
                            ReviewId = 4,
                            Author = "John Snow",
                            City = "Tomsk",
                            Country = "Russia",
                            Rating = 2,
                            Text = "Cold city"
                        },
                        new
                        {
                            ReviewId = 5,
                            Author = "A. Lukashenko",
                            City = "Mogilev",
                            Country = "Belarus",
                            Rating = 1,
                            Text = "Terrible city"
                        },
                        new
                        {
                            ReviewId = 6,
                            Author = "Serge Bash",
                            City = "Minsk",
                            Country = "Belarus",
                            Rating = 1,
                            Text = "OK city"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
